### ISSUE TITLE
Spanish Dictionary requires a login

### ISSUE THREAD

**Issue by Torvicio** [JihongJu/ulauncher-1dictionary#2]
The Spanish dictionary listed (https://www.spanishdict.com/translate/%s?langFrom=es) apparently requires a login.  I did not know that and the default installation of this extension lists english and spanish as default languages. I was frustrated with this extension until I discovered the error.  Thank you so much for developing this extension.  It is very very useful, however the default settings may cause some frustration for many.

**Comment by JihongJu** [comment]
Hi,

It could be that the website only allows a max number of free queries per day. If you dislike that dictionary service, feel free to switch to another one in the extension configuration panel:

 Preferences > Extensions > 1Dictionary > Scroll down a bit > Edit and Save:
 
 
![image](https://user-images.githubusercontent.com/8668792/110956671-24e97e80-834b-11eb-8a73-3598638912b6.png)
